const colors = {
  brand: '#f5218e',
  brandHover: '#d3197a',
  brandActive: '#b01365',
  brandSoft: '#fceef5',
  brandSubtle: '#fff7fb',
  brandGlow: '#fce1ef',
  ink: '#140610',
  text: '#343a46',
  textMuted: '#606a78',
  surface: '#ffffff',
  surfaceSoft: '#faf7f9',
  surfaceTranslucent: 'rgba(255, 255, 255, 0.96)',
  surfaceSoftTranslucent: 'rgba(250, 247, 249, 0.94)',
  border: '#dedee5',
  borderStrong: '#aeb4bd',
  focus: '#a80e5e',
  success: '#16784c',
  successSoft: '#e4f5ec',
  warning: '#8a4d00',
  warningSoft: '#fff2d8',
  danger: '#b42318',
  dangerHover: '#8f1b13',
  dangerSoft: '#ffebe9',
  info: '#315b8a',
  infoSoft: '#eaf2fb',
  scrim: 'rgba(20, 6, 16, 0.58)',
  skeletonHighlight: 'rgba(255, 255, 255, 0.72)',
} as const;

export const brandTokens = {
  // The original aliases remain available while the existing shell migrates.
  pink: colors.brand,
  ink: colors.ink,
  slate: colors.text,
  color: colors,
  spacing: {
    1: '0.25rem',
    2: '0.5rem',
    3: '0.75rem',
    4: '1rem',
    5: '1.25rem',
    6: '1.5rem',
    8: '2rem',
    10: '2.5rem',
    12: '3rem',
    16: '4rem',
  },
  radius: {
    small: '0.625rem',
    medium: '1rem',
    large: '1.5rem',
    pill: '999px',
  },
  typography: {
    body: 'var(--font-inter), Inter, system-ui, sans-serif',
    display: 'var(--font-khand), Khand, system-ui, sans-serif',
    size: {
      small: '0.875rem',
      body: '1rem',
      lead: '1.125rem',
      title: '1.5rem',
    },
  },
  elevation: {
    small: '0 1px 2px rgba(20, 6, 16, 0.06), 0 4px 12px rgba(20, 6, 16, 0.04)',
    medium: '0 12px 32px rgba(20, 6, 16, 0.1)',
    navigation: '0 -8px 28px rgba(20, 6, 16, 0.08)',
    overlay: '0 24px 64px rgba(20, 6, 16, 0.2)',
  },
  zIndex: {
    base: 0,
    sticky: 20,
    overlay: 100,
    toast: 200,
    skipLink: 300,
  },
  motion: {
    fast: '150ms',
    normal: '220ms',
    slow: '320ms',
    easing: 'cubic-bezier(0.22, 0.61, 0.36, 1)',
  },
  touchTarget: '2.75rem',
  admin: {
    color: {
      brand: colors.brand,
      primary: colors.brandActive,
      primaryHover: colors.focus,
      ink: colors.ink,
      text: colors.text,
      textMuted: colors.textMuted,
      canvas: colors.surfaceSoft,
      surface: colors.surface,
      surfaceBrand: colors.brandSoft,
      border: colors.border,
      borderStrong: colors.borderStrong,
      focus: colors.focus,
      success: colors.success,
      successSoft: colors.successSoft,
      warning: colors.warning,
      warningSoft: colors.warningSoft,
      danger: colors.danger,
      dangerSoft: colors.dangerSoft,
      info: colors.info,
      infoSoft: colors.infoSoft,
    },
    typography: {
      family: 'var(--font-inter), Inter, system-ui, sans-serif',
      h1: '700 2rem/2.375rem var(--font-inter), Inter, system-ui, sans-serif',
      h2: '700 1.5rem/1.875rem var(--font-inter), Inter, system-ui, sans-serif',
      h3: '700 1.125rem/1.5rem var(--font-inter), Inter, system-ui, sans-serif',
      body: '400 1rem/1.5rem var(--font-inter), Inter, system-ui, sans-serif',
      label:
        '600 0.875rem/1.25rem var(--font-inter), Inter, system-ui, sans-serif',
    },
    spacing: {
      1: '0.25rem',
      2: '0.5rem',
      3: '0.75rem',
      4: '1rem',
      6: '1.5rem',
      8: '2rem',
      10: '2.5rem',
      12: '3rem',
    },
    radius: {
      control: '0.625rem',
      panel: '0.875rem',
      dialog: '1rem',
      pill: '999px',
    },
    motion: {
      feedback: '150ms',
      overlay: '220ms',
      easing: 'cubic-bezier(0.22, 0.61, 0.36, 1)',
    },
  },
} as const;

export type BrandTokens = typeof brandTokens;
