/** Exact Czech first-name forms. No gender inference, suffix rules or full-name parsing.
 * Reference: https://prirucka.ujc.cas.cz/?id=850
 * Add unfamiliar names only with a checked vocative; user preference always wins.
 */
const forms: Readonly<Record<string, string>> = Object.freeze({
  Adam: 'Adame',
  Adrian: 'Adriane',
  Adriana: 'Adriano',
  Alena: 'Aleno',
  Aleš: 'Aleši',
  Alexandra: 'Alexandro',
  Alice: 'Alice',
  Alžběta: 'Alžběto',
  Andrea: 'Andreo',
  Aneta: 'Aneto',
  Anežka: 'Anežko',
  Anna: 'Anno',
  Antonín: 'Antoníne',
  Barbora: 'Barboro',
  Beáta: 'Beáto',
  Blanka: 'Blanko',
  Bohumil: 'Bohumile',
  Bohuslav: 'Bohuslave',
  Boris: 'Borisi',
  Božena: 'Boženo',
  Dagmar: 'Dagmar',
  Dalibor: 'Dalibore',
  Dana: 'Dano',
  Daniel: 'Danieli',
  Daniela: 'Danielo',
  David: 'Davide',
  Denisa: 'Deniso',
  Dominik: 'Dominiku',
  Dominika: 'Dominiko',
  Dušan: 'Dušane',
  Eduard: 'Eduarde',
  Eliška: 'Eliško',
  Emil: 'Emile',
  Emílie: 'Emílie',
  Erika: 'Eriko',
  Eva: 'Evo',
  Filip: 'Filipe',
  František: 'Františku',
  Gabriela: 'Gabrielo',
  Hana: 'Hano',
  Helena: 'Heleno',
  Hynek: 'Hynku',
  Igor: 'Igore',
  Ilona: 'Ilono',
  Irena: 'Ireno',
  Ivana: 'Ivano',
  Iveta: 'Iveto',
  Ivo: 'Ivo',
  Ivona: 'Ivono',
  Jakub: 'Jakube',
  Jan: 'Jane',
  Jana: 'Jano',
  Jaromír: 'Jaromíre',
  Jaroslav: 'Jaroslave',
  Jaroslava: 'Jaroslavo',
  Jindřich: 'Jindřichu',
  Jiří: 'Jiří',
  Jiřina: 'Jiřino',
  Josef: 'Josefe',
  Jozef: 'Jozefe',
  Julie: 'Julie',
  Kamil: 'Kamile',
  Kamila: 'Kamilo',
  Karel: 'Karle',
  Karolína: 'Karolíno',
  Kateřina: 'Kateřino',
  Klára: 'Kláro',
  Kristina: 'Kristino',
  Kristýna: 'Kristýno',
  Ladislav: 'Ladislave',
  Laura: 'Lauro',
  Lenka: 'Lenko',
  Leoš: 'Leoši',
  Libor: 'Libore',
  Libuše: 'Libuše',
  Lucie: 'Lucie',
  Luděk: 'Luďku',
  Ludmila: 'Ludmilo',
  Lukáš: 'Lukáši',
  Magdaléna: 'Magdaléno',
  Marcela: 'Marcelo',
  Marek: 'Marku',
  Margareta: 'Margareto',
  Marie: 'Marie',
  Markéta: 'Markéto',
  Martin: 'Martine',
  Martina: 'Martino',
  Matěj: 'Matěji',
  Matyáš: 'Matyáši',
  Michaela: 'Michaelo',
  Michal: 'Michale',
  Milan: 'Milane',
  Milena: 'Mileno',
  Miloš: 'Miloši',
  Miloslav: 'Miloslave',
  Miroslav: 'Miroslave',
  Miroslava: 'Miroslavo',
  Monika: 'Moniko',
  Natálie: 'Natálie',
  Nela: 'Nelo',
  Oldřich: 'Oldřichu',
  Olga: 'Olgo',
  Ondřej: 'Ondřeji',
  Ota: 'Oto',
  Otakar: 'Otakare',
  Patrik: 'Patriku',
  Pavel: 'Pavle',
  Pavla: 'Pavlo',
  Pavlína: 'Pavlíno',
  Petr: 'Petře',
  Petra: 'Petro',
  Radek: 'Radku',
  Radim: 'Radime',
  Radka: 'Radko',
  Renata: 'Renato',
  Richard: 'Richarde',
  Robert: 'Roberte',
  Roman: 'Romane',
  Romana: 'Romano',
  Rostislav: 'Rostislave',
  Rudolf: 'Rudolfe',
  Sabina: 'Sabino',
  Sandra: 'Sandro',
  Sára: 'Sáro',
  Silvie: 'Silvie',
  Simona: 'Simono',
  Sofie: 'Sofie',
  Soňa: 'Soňo',
  Stanislav: 'Stanislave',
  Šárka: 'Šárko',
  Šimon: 'Šimone',
  Štěpán: 'Štěpáne',
  Štěpánka: 'Štěpánko',
  Tereza: 'Terezo',
  Tomáš: 'Tomáši',
  Václav: 'Václave',
  Vendula: 'Vendulo',
  Věra: 'Věro',
  Veronika: 'Veroniko',
  Viktor: 'Viktore',
  Viktorie: 'Viktorie',
  Vilém: 'Viléme',
  Vladimír: 'Vladimíre',
  Vladimíra: 'Vladimíro',
  Vlastimil: 'Vlastimile',
  Vojtěch: 'Vojtěchu',
  Zbyněk: 'Zbyňku',
  Zdeněk: 'Zdeňku',
  Zdeňka: 'Zdeňko',
  Zlata: 'Zlato',
  Zuzana: 'Zuzano',
  Žaneta: 'Žaneto',
});
const dictionary = new Map(
  Object.entries(forms).map(([name, vocative]) => [
    name.toLocaleLowerCase('cs'),
    vocative,
  ]),
);
const cleanName = (value: string): string | null => {
  const name = value.normalize('NFC').trim();
  return name.length <= 128 &&
    /^[\p{L}\p{M}]+(?:[ '’\-][\p{L}\p{M}]+)*$/u.test(name)
    ? name
    : null;
};

/** null/undefined = automatic; empty string = explicitly no personal greeting. */
export const czechGreeting = (
  firstName?: string | null,
  preferredSalutation?: string | null,
): string => {
  if (preferredSalutation !== null && preferredSalutation !== undefined) {
    const own = cleanName(preferredSalutation);
    return own ? `Dobrý den, ${own},` : 'Dobrý den,';
  }
  const name = firstName ? cleanName(firstName) : null;
  const vocative = name
    ? dictionary.get(name.toLocaleLowerCase('cs'))
    : undefined;
  return vocative ? `Dobrý den, ${vocative},` : 'Dobrý den,';
};
